name: ~CI, single-arch
run-name: CI-${{ inputs.ARCHITECTURE }}
on:
  workflow_call:
    inputs:
      ARCHITECTURE:
        type: string
        required: true
      BUILD_DATE:
        type: string
        description: Build date in YYYY-MM-DD format
        required: false
        default: NOT SPECIFIED
      MANIFEST_ARTIFACT_NAME:
        type: string
        description: Artifact name in current run w/ manifest/patches. Leaving empty uses manifest/patches in current branch
        default: ''
        required: false
    outputs:
      DOCKER_TAGS:
        description: JSON object containing tags of all docker images built
        value: ${{ jobs.collect-docker-tags.outputs.TAGS }}

permissions:
  contents: read # to fetch code
  actions: write # to cancel previous workflows
  packages: write # to upload container

jobs:
  jax:
    runs-on: self-hosted
    steps:
      - name: Invoke JAX and wait for completion
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Build, test, and publish JAX
          token: ${{ secrets.TOKEN }}
          wait-for-completion: true
          inputs: '{"ARCHITECTURE":"${{ inputs.ARCHITECTURE }}","BUILD_DATE":"${{ inputs.BUILD_DATE }}","MANIFEST_ARTIFACT_NAME":"${{ inputs.MANIFEST_ARTIFACT_NAME }}","DOCKER_TAG_FINAL":"${{ github.run_id }}-jax-${{ inputs.ARCHITECTURE }}","DOCKER_TAG_MEALKIT":"${{ github.run_id }}-jax-${{ inputs.ARCHITECTURE }}-mealkit"}'

  pax:
    needs: jax
    runs-on: self-hosted
    steps:
      - name: Invoke PAX and wait for completion
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Build, test, and publish PAX
          token: ${{ secrets.TOKEN }}
          wait-for-completion: true
          inputs: '{"ARCHITECTURE":"${{ inputs.ARCHITECTURE }}","BUILD_DATE":"${{ inputs.BUILD_DATE }}","MANIFEST_ARTIFACT_NAME":"${{ inputs.MANIFEST_ARTIFACT_NAME }}","BASE_UMAE":"${{ github.run_id }}-jax-${{ inputs.ARCHITECTURE }}-mealkit}'
