name: watchdog

on:
  issue_comment:
    types: [created]

jobs:
  woof:
    runs-on: ubuntu-22.04
    if: >
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/ci') &&
      contains('ko3n1g,nouiz,joker-eph,yhtang,terrykong,hemildesai,chaserileyroberts,CliveUnger,DwarKapex,mingxu1067,kocchop,SahilJain314,ashors1,maanug-nv,hmonishN,gspschmid', format('{0},', github.actor))
    steps:
      - name: Get PR number
        shell: bash
        id: get-pr-num
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "pr_number=$PR_NUM" >> $GITHUB_OUTPUT
          echo "${{ github.event.commment.user.login }}"

      - name: Get Pull Request Information
        uses: actions/github-script@v6
        id: get-pr-branch
        with:
          result-encoding: string
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ steps.get-pr-num.outputs.pr_number }}
            });
            console.log('Pull Request Information:', pr.data);
            return pr.data.head.ref;

      - name: Trigger `CI` workflow on subset of tests          
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          workflow: "CI"
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-completion: false
          ref: ${{ steps.get-pr-branch.outputs.result }}

      - name: Fetch latest run of `CI`
        shell: bash
        run: |
          workflow_id=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows | jq '.workflows[] | select(.name == "CI") | .id')

          workflow_run_url=$(curl -L \
            -H "Accept: Bapplication/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=ko3n1g/ci/add-watchdog" | jq --argjson workflow_id $workflow_id '[.workflow_runs[] | select(.workflow_id == $workflow_id and .actor.login == "github-actions[bot]")][0].html_url' | tr -d '"')

          echo "Click [here]($workflow_run_url) to navigate to the workflow run." >> $GITHUB_STEP_SUMMARY